name: Incorporate
main: com.stephenmac.incorporate.Incorporate
version: 0.2
depend: [Vault]
commands:
  inc:
    description: Incorporate Commands
    usage: /inc <action> [arguments]
    permission: inc.user
permissions:
  inc.user:
    description: Gives access to incorporate commands
    default: true